<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <IsPackable>false</IsPackable>
        <GenerateTestingPlatformEntryPoint>false</GenerateTestingPlatformEntryPoint>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Program.fs"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Partas.Testing\Partas.Testing.fsproj"/>
        <ProjectReference Include="..\..\src\Partas.TestingPlatform.Trx\Partas.TestingPlatform.Trx.fsproj"/>
    </ItemGroup>

</Project>
