<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(PartasTargetFrameworks)</TargetFrameworks>
        <LangVersion>latest</LangVersion>
        <PackageId>Partas.Testing</PackageId>
        <Title>Partas.Testing</Title>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Library.fs"/>
        <None Include="../../README.md" Pack="true" PackagePath="\"/>
    </ItemGroup>

</Project>
