<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(PartasTargetFrameworks)</TargetFrameworks>
        <LangVersion>latest</LangVersion>
        <PackageId>Partas.Testing</PackageId>
        <Title>Partas.Testing</Title>
        <PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Dsl.fs"/>
        <Compile Include="Expect.fs"/>
        <Compile Include="Focus.fs"/>
        <Compile Include="Runner.fs"/>
        <Compile Include="Entry.fs"/>
        <None Include="../../README.md" Pack="true" PackagePath="\"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Partas.TestingPlatform\Partas.TestingPlatform.fsproj"/>
    </ItemGroup>

</Project>
