<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <IsPackable>false</IsPackable>
        <GenerateProgramFile>false</GenerateProgramFile>
        <RootNamespace>Partas.TestingPlatform.CommandLine.Tests</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="CommandLineOptionsTests.fs"/>
        <Compile Include="Main.fs"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Expecto" Version="11.0.0-alpha8"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../../src/Partas.TestingPlatform.CommandLine/Partas.TestingPlatform.CommandLine.fsproj"/>
    </ItemGroup>

</Project>
